name: "Conservative Portfolio"
description: "Conservative allocation focused on capital preservation and income generation"

# Configuration for PortfolioBuilderMultiplicative
builder_settings:
  allow_shorts: false
  normalize_to_relative: true
  proportional_renormalize: true
  weight_reconcile_policy: "respect_parent"
  delimiter: "/"
  root_id: "TOTAL"

# Data source configuration
data_sources:
  portfolio_data: "config/data/portfolio.parquet"
  factor_returns: "config/data/factor_returns.parquet"

# DataFrame column mappings
data_structure:
  component_id_column: "component_id"
  date_column: "date"
  portfolio_weight_column: "portfolio_weight"
  benchmark_weight_column: "benchmark_weight"
  portfolio_return_column: "portfolio_return"
  benchmark_return_column: "benchmark_return"

# Portfolio component hierarchy for builder
components:
  - path: "TOTAL"
    component_type: "node"
    is_overlay: false
    name: "Total Portfolio"

  - path: "TOTAL/IG"
    component_type: "leaf"
    is_overlay: false
    name: "Investment Grade Bonds"

  - path: "TOTAL/CA"
    component_type: "leaf"
    is_overlay: false
    name: "Cash & Money Market"

  - path: "TOTAL/EQLIKE"
    component_type: "node"
    is_overlay: false
    name: "Conservative Equity"

  - path: "TOTAL/EQLIKE/EQDM"
    component_type: "node"
    is_overlay: false
    name: "Low Volatility Equity"

  - path: "TOTAL/EQLIKE/EQDM/EQDMLC"
    component_type: "leaf"
    is_overlay: false
    name: "Large Cap Dividend Stocks"

# Analysis settings
analysis_settings:
  default_date_range: "latest_year"
  annualized: true
  currency: "USD"
  risk_model: "factor_based"
  factor_subset: ["Market", "LowVol", "Quality", "Value"]