# Path configuration for deployment flexibility
paths:
  # Base directory for all resources (can be overridden via MAVERICK_BASE_DIR env var)
  # ".." means parent of config directory (the maverick app root)
  base_dir: ".."
  # Subdirectories relative to base_dir
  config_dir: "config"
  data_dir: "data" 
  graphs_dir: "graphs"

risk_model:
  default: "macro0"
  available:
    - "macro0"
    - "macro1"
    - "macro2"
    - "equity1"
    - "equity2"
    - "Market"

portfolio: {}

portfolio_graphs:
  default: "strategic_portfolio"
  available:
    - "strategic_portfolio"
    - "liquid_portfolio"

analysis:
  annualized: true
  frequency: "daily"
  currency: "SEK"
  risk_model_type: "factor_based"

ui_defaults:
  lens: "active"
  show_top_n_factors: 8
  show_top_n_assets: 8
  default_date_range: "latest_year"

# Data sources - paths will be resolved relative to base_dir
data_sources:
  factor_returns: "data/factor_returns_all.parquet"

# Portfolio graph configurations - paths will be resolved relative to base_dir
portfolio_graph_configs:
  strategic_portfolio: "graphs/strategic_portfolio.yaml"
  liquid_portfolio: "graphs/liquid_portfolio.yaml"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Advanced settings
computation:
  euler_identity_tolerance: 0.01
  min_observations: 100
  factor_exposure_threshold: 0.001

# Data validation settings
validation:
  max_missing_data_pct: 5.0
  min_portfolio_components: 3
  max_hierarchy_depth: 10